'use strict';

/**
 * Nouveautés présentées une fois au joueur après une mise à jour du launcher.
 * Une version absente de cette liste ne déclenche aucune fenêtre.
 */
const CHANGELOG = {
  '1.6.0': {
    title: 'Le grand final',
    items: [
      ['Shaders', 'Installe et active un shader en un clic : Complementary, BSL, MakeUp…'],
      ['Fond d’écran perso', 'Tes propres captures d’écran en fond du launcher.'],
      ['Mods du serveur', 'La liste complète des mods du modpack, avec recherche.'],
      ['Changements du modpack', 'Le launcher t’indique les mods ajoutés ou retirés.'],
      ['Vitesse de téléchargement', 'Rapide, normale ou économe pour ne pas saturer ta connexion.'],
      ['Mises à jour en avance', 'Le modpack se met à jour dès l’ouverture : JOUER est immédiat.'],
      ['Heure de fin', 'Les longs téléchargements affichent l’heure à laquelle ils finiront.'],
      ['Étapes du lancement', 'Suis le lancement étape par étape, de Java au démarrage.'],
      ['Derniers plantages', 'Retrouve tes plantages récents et copie-les pour le staff.'],
      ['Graphismes automatiques', 'À ta première partie, les graphismes s’adaptent à ton PC.'],
      ['Joueurs vus récemment', 'Retrouve qui est passé sur le serveur ces derniers jours.'],
      ['Nouveaux succès', 'Oiseau de nuit, Pilier du royaume, Collectionneur et Esthète.'],
      ['Partager mes stats', 'Copie tes stats pour les montrer à tes amis.'],
      ['Aide', 'Les réponses aux questions fréquentes, directement dans le launcher.'],
      ['Contraste élevé', 'Des textes et bordures plus lisibles.'],
      ['Couleur d’accent', 'Rouge, or, bleu ou vert : choisis la couleur du launcher.'],
      ['Nettoyage automatique', 'Les vieux journaux disparaissent chaque semaine, tout seuls.'],
      ['Sélections rapides', 'Essentiels, Exploration ou Immersion : les bons mods en un clic.'],
    ],
  },
  '1.5.0': {
    title: 'Succès, pauses et partage',
    items: [
      ['Succès', 'Débloque des succès en jouant : Habitué, Nuit blanche, Fidèle…'],
      ['Série de jours', 'Ton profil compte les jours de jeu d’affilée, et ton record.'],
      ['Rappel de pause', 'Une notification toutes les 1, 2 ou 3 heures de jeu, si tu le souhaites.'],
      ['Ne pas déranger', 'Plus de notification d’amis ni d’actualités pendant la partie.'],
      ['Sauvegarde des réglages', 'Sauvegarde et restaure tes graphismes, ton son et tes touches.'],
      ['Recherche de mods', 'Cherche un mod optionnel, active-les ou retire-les tous d’un clic.'],
      ['Partager une capture', 'Copie une capture pour la coller sur Discord, ou mets-la à la corbeille.'],
      ['Visite guidée', 'Une présentation du launcher pour bien démarrer.'],
      ['Inviter un ami', 'Un message prêt à envoyer, avec le lien du launcher et le Discord.'],
      ['Raccourci « Jouer »', 'Un raccourci sur le bureau qui lance directement le jeu.'],
    ],
  },
  '1.4.0': {
    title: 'Ton profil et tes amis',
    items: [
      ['Profil', 'Clique sur ton pseudo : temps de jeu, parties, plus longue partie et moyenne.'],
      ['Activité de la semaine', 'Un graphique de ton temps de jeu sur les 7 derniers jours.'],
      ['Amis', 'Ajoute tes amis : ils passent en premier et tu es prévenu quand ils se connectent.'],
      ['Graphismes en un clic', 'Performance, Équilibré ou Qualité, dans les réglages.'],
      ['Réinitialiser les options', 'Un réglage casse l’affichage du jeu ? Remets tout par défaut.'],
      ['Afficher le jeu', 'Pendant la partie, le bouton ramène Minecraft au premier plan.'],
      ['Actualités en direct', 'Une notification dès qu’une actualité est publiée.'],
      ['Mise à jour à la demande', 'Recherche une nouvelle version du launcher quand tu veux.'],
      ['Taille de l’interface', 'Agrandis ou réduis le launcher, de 90 à 125 %.'],
      ['Sons', 'De petits sons au lancement, quand le jeu est prêt et quand un ami arrive.'],
    ],
  },
  '1.3.0': {
    title: 'La grande mise à jour',
    items: [
      ['Menu Aethoria', 'Minecraft s’ouvre sur un menu dédié : rejoindre Aethoria ou régler les options.'],
      ['Joueurs connectés','Clique sur l’état du serveur pour voir qui est en ligne.'],
      ['Latence du serveur', 'Ton ping s’affiche à côté du nombre de joueurs.'],
      ['Alerte de retour', 'Serveur hors ligne ? « Me prévenir » t’avertit dès qu’il revient.'],
      ['Temps de jeu', 'Ton temps de jeu total s’affiche sous ton pseudo.'],
      ['Captures d’écran', 'Toutes tes captures (F2) dans l’onglet Captures.'],
      ['Rapport de plantage', 'Un clic copie un rapport complet à envoyer au staff.'],
      ['Barre des tâches', 'La progression du téléchargement s’affiche dans la barre des tâches.'],
      ['Notifications', 'Windows te prévient quand le jeu est prêt.'],
      ['Pendant la partie', 'Le launcher peut rester ouvert, se ranger près de l’horloge ou se fermer.'],
      ['Forcer l’arrêt', 'Le jeu est bloqué ? Ferme-le depuis le launcher.'],
      ['Taille de la fenêtre', 'Choisis la résolution du jeu, ou le plein écran.'],
      ['Jeu en français', 'Minecraft s’ouvre directement en français.'],
      ['Nettoyage', 'Libère la place prise par les anciens journaux et plantages.'],
      ['Tester ma connexion', 'Vérifie en un clic Internet, le serveur, le disque et la mémoire.'],
      ['Vérifier les fichiers', 'Contrôle et répare le jeu sans tout retélécharger.'],
      ['Prochaine mise à jour', 'L’accueil indique ce qu’il reste à télécharger avant de jouer.'],
      ['Icône près de l’horloge', 'Le launcher reste accessible depuis la zone de notification.'],
      ['Démarrer avec Windows', 'Le launcher peut s’ouvrir discrètement au démarrage du PC.'],
      ['Fond d’écran', 'Garde ton paysage préféré, ou laisse-les défiler.'],
      ['Mode léger', 'Sans animations ni flou, pour les PC modestes.'],
      ['Actualités', 'Un badge « Nouveau » signale ce que tu n’as pas encore lu.'],
      ['Liste multijoueur', 'Aethoria apparaît dans la liste des serveurs de Minecraft.'],
      ['Raccourcis clavier', 'Entrée pour jouer, F5 pour actualiser, Échap pour fermer.'],
      ['Ces nouveautés', 'Retrouve-les à tout moment en cliquant sur le numéro de version.'],
    ],
  },
};
